// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: transactionEVM.proto

package transaction

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	transaction "github.com/multiversx/mx-chain-core-go/data/transaction"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TransactionEVM struct {
	Transaction  *transaction.Transaction `protobuf:"bytes,1,opt,name=Transaction,proto3" json:"transaction"`
	RcvAliasAddr []byte                   `protobuf:"bytes,2,opt,name=RcvAliasAddr,proto3" json:"rcvAliasAddr,omitempty"`
	SndAliasAddr []byte                   `protobuf:"bytes,3,opt,name=SndAliasAddr,proto3" json:"sndAliasAddr,omitempty"`
	OriginalData []byte                   `protobuf:"bytes,4,opt,name=OriginalData,proto3" json:"originalData,omitempty"`
}

func (m *TransactionEVM) Reset()      { *m = TransactionEVM{} }
func (*TransactionEVM) ProtoMessage() {}
func (*TransactionEVM) Descriptor() ([]byte, []int) {
	return fileDescriptor_8dccbb57196fb507, []int{0}
}
func (m *TransactionEVM) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TransactionEVM) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *TransactionEVM) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionEVM.Merge(m, src)
}
func (m *TransactionEVM) XXX_Size() int {
	return m.Size()
}
func (m *TransactionEVM) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionEVM.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionEVM proto.InternalMessageInfo

func (m *TransactionEVM) GetTransaction() *transaction.Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *TransactionEVM) GetRcvAliasAddr() []byte {
	if m != nil {
		return m.RcvAliasAddr
	}
	return nil
}

func (m *TransactionEVM) GetSndAliasAddr() []byte {
	if m != nil {
		return m.SndAliasAddr
	}
	return nil
}

func (m *TransactionEVM) GetOriginalData() []byte {
	if m != nil {
		return m.OriginalData
	}
	return nil
}

func init() {
	proto.RegisterType((*TransactionEVM)(nil), "proto.TransactionEVM")
}

func init() { proto.RegisterFile("transactionEVM.proto", fileDescriptor_8dccbb57196fb507) }

var fileDescriptor_8dccbb57196fb507 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4e, 0x32, 0x41,
	0x10, 0xc7, 0x77, 0xf9, 0x3e, 0x2d, 0x0e, 0xa2, 0xc9, 0xc5, 0x18, 0x42, 0x31, 0x10, 0x2b, 0x0a,
	0x8f, 0x4b, 0xb4, 0x37, 0x81, 0x48, 0x69, 0x4c, 0xc0, 0x58, 0xd8, 0x2d, 0x77, 0xe7, 0xb2, 0x09,
	0xb7, 0x4b, 0xf6, 0x16, 0x82, 0x9d, 0x8f, 0x60, 0xe7, 0x2b, 0xf8, 0x28, 0x96, 0x94, 0x54, 0xc4,
	0xdb, 0x6b, 0x0c, 0x15, 0x8f, 0x60, 0xd8, 0x2b, 0x6e, 0xa8, 0x76, 0xe6, 0xbf, 0xbf, 0xdf, 0x64,
	0x32, 0xde, 0x85, 0xd1, 0x4c, 0x66, 0x2c, 0x32, 0x42, 0xc9, 0xe1, 0xf3, 0x43, 0x6f, 0xae, 0x95,
	0x51, 0xfe, 0x89, 0x7b, 0x5a, 0x01, 0x17, 0x66, 0xba, 0x98, 0xf4, 0x22, 0x95, 0x86, 0x5c, 0x71,
	0x15, 0xba, 0x78, 0xb2, 0x78, 0x75, 0x9d, 0x6b, 0x5c, 0x55, 0x5a, 0xad, 0x31, 0xc2, 0xd3, 0xc5,
	0xcc, 0x88, 0x65, 0xa2, 0xb3, 0x55, 0x98, 0xae, 0x82, 0x68, 0xca, 0x84, 0x0c, 0x22, 0xa5, 0x93,
	0x20, 0x53, 0xcb, 0x44, 0x27, 0x82, 0xcb, 0x80, 0xab, 0x30, 0x66, 0x86, 0x85, 0x68, 0x03, 0x5c,
	0x97, 0x43, 0xaf, 0x3e, 0x6b, 0xde, 0xd9, 0xd3, 0xd1, 0x8e, 0xfe, 0xd0, 0xab, 0xa3, 0xa4, 0x49,
	0x3b, 0xb4, 0x5b, 0xbf, 0xf1, 0x4b, 0xbe, 0x87, 0x7e, 0x06, 0xe7, 0xbb, 0x6d, 0xbb, 0x8e, 0x46,
	0x8e, 0xb0, 0xe7, 0xdf, 0x79, 0x8d, 0x51, 0xb4, 0xec, 0xcf, 0x04, 0xcb, 0xfa, 0x71, 0xac, 0x9b,
	0xb5, 0x0e, 0xed, 0x36, 0x06, 0xad, 0xdd, 0xb6, 0x7d, 0xa9, 0x51, 0x7e, 0xad, 0x52, 0x61, 0x92,
	0x74, 0x6e, 0xde, 0x46, 0x47, 0xfc, 0xc1, 0x1f, 0xcb, 0xb8, 0xf2, 0xff, 0x55, 0x7e, 0x86, 0x72,
	0xec, 0x63, 0xfe, 0xe0, 0x3f, 0x6a, 0xc1, 0x85, 0x64, 0xb3, 0x7b, 0x66, 0x58, 0xf3, 0x7f, 0xe5,
	0x2b, 0x94, 0x63, 0x1f, 0xf3, 0x83, 0xe1, 0x3a, 0x07, 0xb2, 0xc9, 0x81, 0xec, 0x73, 0xa0, 0xef,
	0x16, 0xe8, 0x97, 0x05, 0xfa, 0x6d, 0x81, 0xae, 0x2d, 0xd0, 0x8d, 0x05, 0xfa, 0x63, 0x81, 0xfe,
	0x5a, 0x20, 0x7b, 0x0b, 0xf4, 0xa3, 0x00, 0xb2, 0x2e, 0x80, 0x6c, 0x0a, 0x20, 0x2f, 0xf8, 0x26,
	0x93, 0x53, 0x77, 0xb7, 0xdb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0x71, 0xa0, 0xb9, 0x0a,
	0x02, 0x00, 0x00,
}

func (this *TransactionEVM) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TransactionEVM)
	if !ok {
		that2, ok := that.(TransactionEVM)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Transaction.Equal(that1.Transaction) {
		return false
	}
	if !bytes.Equal(this.RcvAliasAddr, that1.RcvAliasAddr) {
		return false
	}
	if !bytes.Equal(this.SndAliasAddr, that1.SndAliasAddr) {
		return false
	}
	if !bytes.Equal(this.OriginalData, that1.OriginalData) {
		return false
	}
	return true
}
func (this *TransactionEVM) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&transaction.TransactionEVM{")
	if this.Transaction != nil {
		s = append(s, "Transaction: "+fmt.Sprintf("%#v", this.Transaction)+",\n")
	}
	s = append(s, "RcvAliasAddr: "+fmt.Sprintf("%#v", this.RcvAliasAddr)+",\n")
	s = append(s, "SndAliasAddr: "+fmt.Sprintf("%#v", this.SndAliasAddr)+",\n")
	s = append(s, "OriginalData: "+fmt.Sprintf("%#v", this.OriginalData)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringTransactionEVM(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *TransactionEVM) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TransactionEVM) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TransactionEVM) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OriginalData) > 0 {
		i -= len(m.OriginalData)
		copy(dAtA[i:], m.OriginalData)
		i = encodeVarintTransactionEVM(dAtA, i, uint64(len(m.OriginalData)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SndAliasAddr) > 0 {
		i -= len(m.SndAliasAddr)
		copy(dAtA[i:], m.SndAliasAddr)
		i = encodeVarintTransactionEVM(dAtA, i, uint64(len(m.SndAliasAddr)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RcvAliasAddr) > 0 {
		i -= len(m.RcvAliasAddr)
		copy(dAtA[i:], m.RcvAliasAddr)
		i = encodeVarintTransactionEVM(dAtA, i, uint64(len(m.RcvAliasAddr)))
		i--
		dAtA[i] = 0x12
	}
	if m.Transaction != nil {
		{
			size, err := m.Transaction.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTransactionEVM(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTransactionEVM(dAtA []byte, offset int, v uint64) int {
	offset -= sovTransactionEVM(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TransactionEVM) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Transaction != nil {
		l = m.Transaction.Size()
		n += 1 + l + sovTransactionEVM(uint64(l))
	}
	l = len(m.RcvAliasAddr)
	if l > 0 {
		n += 1 + l + sovTransactionEVM(uint64(l))
	}
	l = len(m.SndAliasAddr)
	if l > 0 {
		n += 1 + l + sovTransactionEVM(uint64(l))
	}
	l = len(m.OriginalData)
	if l > 0 {
		n += 1 + l + sovTransactionEVM(uint64(l))
	}
	return n
}

func sovTransactionEVM(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTransactionEVM(x uint64) (n int) {
	return sovTransactionEVM(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *TransactionEVM) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TransactionEVM{`,
		`Transaction:` + strings.Replace(fmt.Sprintf("%v", this.Transaction), "Transaction", "transaction.Transaction", 1) + `,`,
		`RcvAliasAddr:` + fmt.Sprintf("%v", this.RcvAliasAddr) + `,`,
		`SndAliasAddr:` + fmt.Sprintf("%v", this.SndAliasAddr) + `,`,
		`OriginalData:` + fmt.Sprintf("%v", this.OriginalData) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringTransactionEVM(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *TransactionEVM) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransactionEVM
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TransactionEVM: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TransactionEVM: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transaction", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransactionEVM
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTransactionEVM
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTransactionEVM
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Transaction == nil {
				m.Transaction = &transaction.Transaction{}
			}
			if err := m.Transaction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RcvAliasAddr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransactionEVM
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTransactionEVM
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTransactionEVM
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RcvAliasAddr = append(m.RcvAliasAddr[:0], dAtA[iNdEx:postIndex]...)
			if m.RcvAliasAddr == nil {
				m.RcvAliasAddr = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SndAliasAddr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransactionEVM
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTransactionEVM
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTransactionEVM
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SndAliasAddr = append(m.SndAliasAddr[:0], dAtA[iNdEx:postIndex]...)
			if m.SndAliasAddr == nil {
				m.SndAliasAddr = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginalData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTransactionEVM
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTransactionEVM
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTransactionEVM
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginalData = append(m.OriginalData[:0], dAtA[iNdEx:postIndex]...)
			if m.OriginalData == nil {
				m.OriginalData = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTransactionEVM(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthTransactionEVM
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthTransactionEVM
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTransactionEVM(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTransactionEVM
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTransactionEVM
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTransactionEVM
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTransactionEVM
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTransactionEVM
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTransactionEVM
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTransactionEVM        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTransactionEVM          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTransactionEVM = fmt.Errorf("proto: unexpected end of group")
)
